package com.example.xlm.mydrawerdemo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHILD_FORM".
 */
public class ChildForm {

    /** Not-null value. */
    private String id;
    private String fgroup;
    private String sort;
    private String name;
    private String showName;
    private String msg;
    private String interval;
    private String createAt;
    private String updateAt;
    private String status;

    public ChildForm() {
    }

    public ChildForm(String id, String fgroup, String sort, String name, String showName, String msg, String interval, String createAt, String updateAt, String status) {
        this.id = id;
        this.fgroup = fgroup;
        this.sort = sort;
        this.name = name;
        this.showName = showName;
        this.msg = msg;
        this.interval = interval;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.status = status;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getFgroup() {
        return fgroup;
    }

    public void setFgroup(String fgroup) {
        this.fgroup = fgroup;
    }

    public String getSort() {
        return sort;
    }

    public void setSort(String sort) {
        this.sort = sort;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getShowName() {
        return showName;
    }

    public void setShowName(String showName) {
        this.showName = showName;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getInterval() {
        return interval;
    }

    public void setInterval(String interval) {
        this.interval = interval;
    }

    public String getCreateAt() {
        return createAt;
    }

    public void setCreateAt(String createAt) {
        this.createAt = createAt;
    }

    public String getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
